# GitHub Sponsors configuration
# Uncomment and configure when ready to accept sponsorships

# github: [moshehbenavraham]
# patreon: # your_patreon_username
# open_collective: # your_open_collective_name
# ko_fi: # your_ko_fi_username
# tidelift: # your_tidelift_platform_name/your_package_name
# community_bridge: # your_community_bridge_project_name
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# otechie: # your_otechie_username
# lfx_crowdfunding: # your_lfx_crowdfunding_project_name
# custom: # ['https://your_custom_link.com']
